Index: linux-3.13/block/Makefile
===================================================================
--- linux-3.13.orig/block/Makefile	2016-04-26 11:00:37.926971957 +0200
+++ linux-3.13/block/Makefile	2016-04-26 11:01:13.136971054 +0200
@@ -7,7 +7,8 @@
 			blk-exec.o blk-merge.o blk-softirq.o blk-timeout.o \
 			blk-iopoll.o blk-lib.o blk-mq.o blk-mq-tag.o \
 			blk-mq-sysfs.o blk-mq-cpu.o blk-mq-cpumap.o ioctl.o \
-			genhd.o scsi_ioctl.o partition-generic.o partitions/
+			genhd.o scsi_ioctl.o partition-generic.o partitions/ \
+			cause_tags.o
 
 obj-$(CONFIG_BLK_DEV_BSG)	+= bsg.o
 obj-$(CONFIG_BLK_DEV_BSGLIB)	+= bsg-lib.o
