--- linux-3.2.51/block/Makefile	2013-09-10 02:57:42.000000000 +0200
+++ ../split-release/release/linux-3.2.51/block/Makefile	2015-09-01 05:42:46.000000000 +0200
@@ -5,7 +5,8 @@
 obj-$(CONFIG_BLOCK) := elevator.o blk-core.o blk-tag.o blk-sysfs.o \
 			blk-flush.o blk-settings.o blk-ioc.o blk-map.o \
 			blk-exec.o blk-merge.o blk-softirq.o blk-timeout.o \
-			blk-iopoll.o blk-lib.o ioctl.o genhd.o scsi_ioctl.o
+			blk-iopoll.o blk-lib.o ioctl.o genhd.o scsi_ioctl.o \
+            cause_tags.o
 
 obj-$(CONFIG_BLK_DEV_BSG)	+= bsg.o
 obj-$(CONFIG_BLK_DEV_BSGLIB)	+= bsg-lib.o
diff -rubBN linux-3.2.51/Documentation/DocBook/media/v4l/fieldseq_tb.pdf ../split-release/release/linux-3.2.51/Documentation/DocBook/media/v4l/fieldseq_tb.pdf
